<?xml version="1.0" encoding="ISO-8859-1" ?>

<!-- DTD: BEGIN -->
<!DOCTYPE form-validation [
<!--
     The "form-validation" element is the root of the configuration file
     hierarchy, and contains nested elements for all of the other
     configuration settings.
-->
<!ELEMENT form-validation (global*, formset*)>

<!--
    The elements defined here are all global and must be nested within a
    "global" element.
-->
<!ELEMENT global (validator*, constant*)>

<!--
     The "validator" element defines what validators objects can be used with
     the fields referenced by the formset elements. The validator element can
     accept 4 properties: name, classname, method, methodparams, msg, depends,
     and jsFunctionName.
-->
<!ELEMENT validator (javascript?)>
<!ATTLIST validator name           CDATA #REQUIRED
                    classname      CDATA #REQUIRED
                    method         CDATA #REQUIRED
                    methodParams   CDATA #REQUIRED
                    msg            CDATA #REQUIRED
                    depends        CDATA #IMPLIED
                    jsFunctionName CDATA #IMPLIED >

<!--
     The "javascript" element defines a JavaScript that can be used to perform
     client-side validators.
-->
<!ELEMENT javascript (#PCDATA)>

<!--
     The "constant" element defines a static value that can be used as
     replacement parameters within "field" elements. The "constant-name" and
     "constant-value" elements define the constant's reference id and replacement
     value.
-->
<!ELEMENT constant (constant-name, constant-value)>
<!ELEMENT constant-name  (#PCDATA)>
<!ELEMENT constant-value (#PCDATA)>

<!--
      The "formset" element defines a set of forms for a locale. Formsets for
      specific locales can override only those fields that change. The
      localization is properly scoped, so that a formset can override just the
      language, or just the country, or both.
-->
<!ELEMENT formset (constant*, form+)>
<!ATTLIST formset language     CDATA #IMPLIED
                  country      CDATA #IMPLIED >

<!--
     The "form" element defines a set of fields to be validated. The name
     corresponds to the identifer the application assigns to the form.
-->
<!ELEMENT form    (field+ )>
<!ATTLIST form    name         CDATA #REQUIRED>

<!--
     The "field" element defines the properties to be validated. In a
     web application, a field would also correspond to a control on
     a HTML form. To validate the properties, the validator works through
     a JavaBean representation. The field element can accept up to 4
     attributes:

     property        The property on the JavaBean corresponding to this
                     field element.

     depends         The comma-delimited list of validators to apply against
                     this field. For the field to succeed, all the
                     validators must succeed.

     page            The JavaBean corresponding to this form may include
                     a page property. Only fields with a "page" attribute
                     value that is equal to or less than the page property
                     on the form JavaBean are processed. This is useful when
                     using a "wizard" approach to completing a large form,
                     to ensure that a page is not skipped.
                     [0]

     indexedListProperty
                     The "indexedListProperty" is the method name that will
                     return an array or a Collection used to retrieve the
                     list and then loop through the list performing the
                     validations for this field.

-->
<!ELEMENT field   (msg|arg0|arg1|arg2|arg3|var)*>
<!ATTLIST field   property CDATA #REQUIRED
                  depends  CDATA #IMPLIED
                  page     CDATA #IMPLIED
                  indexedListProperty CDATA #IMPLIED >

<!--
     The "msg" element defines a custom message key to use when one of the
     validators for this field fails. Each validator has a default message
     property that is used when a corresonding field msg is not specified.
     Each validator applied to a field may have its own msg element.
     The msg element accepts up to three attributes.

      name        The name of the validator corresponding to this msg.

      key         The key that will return the message template from a
                  resource bundle.

      resource    If set to "false", the key is taken to be a literal
                  value rather than a bundle key.
                  [true]
-->
<!ELEMENT msg     EMPTY>
<!ATTLIST msg     name     CDATA #IMPLIED
                  key      CDATA #IMPLIED
                  resource CDATA #IMPLIED >

<!--
     The "arg0" element defines the first replacement value to use with the
     message template for this validator or this field.
     The arg0 element accepts up to three attributes.

      name        The name of the validator corresponding to this msg.

      key         The key that will return the message template from a
                  resource bundle.

      resource    If set to "false", the key is taken to be a literal
                  value rather than a bundle key.
                  [true]
-->
<!ELEMENT arg0    EMPTY>
<!ATTLIST arg0    name     CDATA #IMPLIED
                  key      CDATA #IMPLIED
                  resource CDATA #IMPLIED >

<!--
     The "arg1" element defines the second replacement value to use with the
     message template for this validator or this field.
     The arg1 element accepts up to three attributes.

      name        The name of the validator corresponding to this msg.

      key         The key that will return the message template from a
                  resource bundle.

      resource    If set to "false", the key is taken to be a literal
                  value rather than a bundle key.
                  [true]
-->
<!ELEMENT arg1    EMPTY>
<!ATTLIST arg1    name     CDATA #IMPLIED
                  key      CDATA #IMPLIED
                  resource CDATA #IMPLIED >

<!--
     The "arg2" element defines the third replacement value to use with the
     message template for this validator or this field.
     The arg2 element accepts up to three attributes.

      name        The name of the validator corresponding to this msg.

      key         The key that will return the message template from a
                  resource bundle.

      resource    If set to "false", the key is taken to be a literal
                  value rather than a bundle key.
                  [true]
-->
<!ELEMENT arg2    EMPTY>
<!ATTLIST arg2    name     CDATA #IMPLIED
                  key      CDATA #IMPLIED
                  resource CDATA #IMPLIED >

<!--
     The "arg3" element defines the fourth replacement value to use with the
     message template for this validator or this field.
     The arg0 element accepts up to three attributes.

      name        The name of the validator corresponding to this msg.

      key         The key that will return the message template from a
                  resource bundle.

      resource    If set to "false", the key is taken to be a literal
                  value rather than a bundle key.
                  [true]
-->
<!ELEMENT arg3    EMPTY>
<!ATTLIST arg3    name     CDATA #IMPLIED
                  key      CDATA #IMPLIED
                  resource CDATA #IMPLIED >

<!--
     The "var" element can set parameters that a field may need to pass to
     one of its validators, such as the minimum and maximum values in a
     range validation. These parameters may also be referenced by one of the
     arg? elements using a shell syntax: ${var:var-name}.
-->
<!ELEMENT var (var-name, var-value)>

<!--
     The name of the var parameter to provide to a field's validators.
-->
<!ELEMENT var-name  (#PCDATA)>

<!--
     The value of the var parameter to provide to a field's validators.
-->
<!ELEMENT var-value (#PCDATA)>

]>
<!-- DTD: END -->

<form-validation>

<!--
     This is a blank Validator form file with a commented examples.
-->

    <global>

        <!-- An example global constant
        <constant>
            <constant-name>postalCode</constant-name>
            <constant-value>^\d{5}\d*$</constant-value>
        </constant>
        end example-->
        <!--
        <constant>
            <constant-name>zipCode</constant-name>
            <constant-value>^\d{5}\d*$</constant-value>
        </constant>-->
    </global>

    <formset>
        <form name="applicationForm">
            <field property="name" depends="required">
                <arg0 key="Application Name" resource="false"/>
            </field>
        </form>
        <form name="userForm">
            <field property="username" depends="required">
                <arg0 key="Username" resource="false"/>
            </field>
            <field property="password" depends="required, matchFields">
                <arg0 key="Password" resource="false"/>
                <msg name="matchFields" key="error.user.passwordMatch"/>
                <var>
                  <var-name>secondProperty</var-name>
                  <var-value>confirmPassword</var-value>
                </var>
            </field>
            <field property="role" depends="requiredif">
                <arg0 key="Role" resource="false"/>
                <var>
                    <var-name>field0</var-name>
                    <var-value>username</var-value>
                </var>
                <var>
                    <var-name>fieldTest0</var-name>
                    <var-value>NOTEQUAL</var-value>
                </var>
                <var>
                    <var-name>fieldValue0</var-name>
                    <var-value>admin</var-value>
                </var>
            </field>
        </form>
        <form name="loginForm">
            <field property="username" depends="required">
                <arg0 key="Username" resource="false"/>
            </field>
            <field property="password" depends="required">
                <arg0 key="Password" resource="false"/>
            </field>
        </form>
        <form name="changePasswordForm">
            <field property="oldPassword" depends="required">
                <arg0 key="Old Password" resource="false"/>
            </field>
            <field property="newPassword" depends="required">
                <arg0 key="New Password" resource="false"/>
            </field>
            <field property="confirmPassword" depends="required">
                <arg0 key="Confirm Password" resource="false"/>
            </field>
        </form>
        <form name="alertForm">
            <field property="alertName" depends="required">
                <arg0 key="Alert Name" resource="false"/>
            </field>
            <field property="alertDelivery" depends="required">
                <arg0 key="Alert Delivery" resource="false"/>
            </field>
            <field property="alertSourceType" depends="required">
                <arg0 key="Alert Source Type" resource="false"/>
            </field>
            <field property="expression" depends="required">
                <arg0 key="Source MBean" resource="false"/>
            </field>
        </form>
        <form name="attributeSelectionForm">
            <field property="mbeans" depends="required" page="1" >
                <arg0 key="MBeans" resource="false"/>
                <msg name="required" key="error.select.required"/>
            </field>

            <field property="attributes" depends="required" page="2">
                <arg0 key="Attribute" resource="false"/>
                <msg name="required" key="error.select.required"/>
            </field>
        </form>
        <form name="graphForm">
            <field property="graphName" depends="required">
                <arg0 key="Graph Name" resource="false"/>
            </field>
            <field property="pollInterval" depends="required, long">
                <arg0 key="Polling Interval" resource="false"/>
            </field>
            <field property="scaleFactor" depends="double">
                <arg0 key="Scale Factor" resource="false"/>
            </field>
        </form>
    </formset>
</form-validation>